[package]
name = "abci-client"
version = "0.1.0"
authors = ["amanusk <amanusk@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
restson = "^0.5"
serde = "^1.0"
serde_derive = "^1.0"
curl = "0.4"
